## @file
# GNU/Linux makefile for 'GenCrc32' module build.
#
# Copyright (c) 2007 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

APPNAME = GenCrc32

LIBS = -lCommon

OBJECTS = GenCrc32.o

include $(MAKEROOT)/Makefiles/app.makefile
