## @file
# Windows makefile for 'GenCrc32' module build.
#
# Copyright (c) 2007 - 2010, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
!INCLUDE ..\Makefiles\ms.common

APPNAME = GenCrc32

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = GenCrc32.obj

!INCLUDE ..\Makefiles\ms.app

