## @file
# GNU/Linux makefile for 'GenFfs' module build.
#
# Copyright (c) 2007 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

APPNAME = GenFfs

OBJECTS = GenFfs.o

include $(MAKEROOT)/Makefiles/app.makefile

LIBS = -lCommon

