#!/usr/bin/env bash
#
# This script will exec Brotli tool.
#
# Copyright (c) 2017, Intel Corporation. All rights reserved.<BR>
# This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
QLT="-q 9"
INPUTFLAG=0

for arg; do
  if [ $1 = -d ]
    then
      INPUTFLAG=1
  fi
  if [ $1 = -e ]
    then
      INPUTFLAG=1
      shift
      continue;
  fi
  if [ $1 = -g ]
    then
      ARGS+="$1 $2 "
      shift
      shift
      continue;
  fi
  if [ $1 = -o ]
    then
      ARGS+="$1 $2 "
      shift
      shift
      continue;
  fi
  if [ $1 = -q ]
    then
      QLT="$1 $2 "
      shift
      shift
      continue;
  fi
  if [ $INPUTFLAG -eq 1 ]
    then
      if [ -z $2 ]
        then
          ARGS+="$QLT -i $1 "
          break;
      fi
  fi

ARGS+="$1 "
shift
done

exec Brotli $ARGS
