#!/usr/bin/env bash
#
# This script will exec Brotli tool with -e/-d options.
#
# Copyright (c) 2017 - 2018, Intel Corporation. All rights reserved.<BR>
# This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
QLT="-q 9 -w 22"
ARGS=

while test $# -gt 0
do
  case $1 in
    -e)
      ;;
    -d)
      ARGS+="$1 "
      ;;
    -o|-g)
      ARGS+="$1 $2 "
      shift
      ;;
    -q)
      QLT="$1 $2 "
      shift
      ;;
    *)
      ARGS+="$1 "
      ;;
  esac
  shift
done

exec Brotli $QLT $ARGS
