#!/usr/bin/env bash

full_cmd=${BASH_SOURCE[-1]:-$0} # see http://mywiki.wooledge.org/BashFAQ/028 for a discussion of why $0 is not a good choice here
dir=$(dirname "$full_cmd")
cmd=${full_cmd##*/}

if [ -n "$EDK_TOOLS_PATH" ] && [ -e "$EDK_TOOLS_PATH/Source/C/bin" ]
then
  if [ -e "$EDK_TOOLS_PATH/Source/C/bin/$cmd" ]
  then
    exec "$EDK_TOOLS_PATH/Source/C/bin/$cmd" "$@"
  fi
elif [ -e "$dir/../../Source/C/bin/$cmd" ]
then
  exec "$dir/../../Source/C/bin/$cmd" "$@"
else
  echo "Unable to find the real '$cmd' to run"
  echo "This message was printed by"
  echo "  $0"
  exit 127
fi
