## @file
# GNU/Linux makefile for 'BfmLib' module build.
#
# Copyright (c) 2011-2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

APPNAME = BfmLib

LIBS = -lCommon

OBJECTS = BinFileManager.o BfmLib.o

include $(MAKEROOT)/Makefiles/app.makefile
