## @file
#
# Windows makefile for 'BfmLib' module build.
#
# Copyright (c) 2011-2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent#
##
!INCLUDE ..\Makefiles\ms.common

APPNAME = BfmLib

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = BinFileManager.obj BfmLib.obj

!INCLUDE ..\Makefiles\ms.app

