## @file
# GNU/Linux makefile for 'Common' module build.
#
# Copyright (c) 2007 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

# VPATH = ..

LIBNAME = Common

OBJECTS = \
  BasePeCoff.o \
  BinderFuncs.o \
  CommonLib.o \
  Crc32.o \
  Decompress.o \
  EfiCompress.o \
  EfiUtilityMsgs.o \
  FirmwareVolumeBuffer.o \
  FvLib.o \
  MemoryFile.o \
  MyAlloc.o \
  OsPath.o \
  ParseGuidedSectionTools.o \
  ParseInf.o \
  PeCoffLoaderEx.o \
  SimpleFileParsing.o \
  StringFuncs.o \
  TianoCompress.o

include $(MAKEROOT)/Makefiles/lib.makefile
