## @file GNUmakefile
#
# GNU makefile for 'FCE' module build.
#
# Copyright (c) 2007 - 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

MAKEROOT ?= ..

APPNAME = FCE

OBJECTS = Fce.o Variable.o TimeBasedVariable.o MonotonicBasedVariable.o IfrParse.o Common.o BinaryParse.o BinaryCreate.o Expression.o

include $(MAKEROOT)/Makefiles/app.makefile

LIBS = -lCommon -lm


