## @file
#
# Windows makefile for 'FCE' module build.
#
#Copyright (c) 2011-2019, Intel Corporation. All rights reserved.<BR>
#SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.common

APPNAME = FCE

LIBS = $(LIB_PATH)\Common.lib

OBJECTS =  Fce.obj Variable.obj TimeBasedVariable.obj MonotonicBasedVariable.obj IfrParse.obj Common.obj BinaryParse.obj BinaryCreate.obj Expression.obj

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.app

