## @file
# GNU/Linux makefile for 'FMMT' module build.
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

APPNAME = FMMT

LIBS = -lCommon

OBJECTS = FmmtLib.o Rebase.o FirmwareModuleManagement.o

include $(MAKEROOT)/Makefiles/app.makefile

