## @file
# Windows makefile for 'FMMT' module build.
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

!INCLUDE ..\Makefiles\ms.common

APPNAME = FMMT

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = FirmwareModuleManagement.obj FmmtLib.obj Rebase.obj

!INCLUDE ..\Makefiles\ms.app

