## @file
# Windows makefile for 'GenFv' module build.
#
# Copyright (c) 2007 - 2010, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
!INCLUDE ..\Makefiles\ms.common

APPNAME = GenFv

LIBS = $(LIB_PATH)\Common.lib RpcRT4.lib

OBJECTS = GenFv.obj GenFvInternalLib.obj

!INCLUDE ..\Makefiles\ms.app

