#!/usr/bin/env bash
#
# This script will exec Brotli tool with -e/-d options.
#
# Copyright (c) 2017 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
QLT="-q 9 -w 22"
ARGS=

while test $# -gt 0
do
  case $1 in
    -e)
      ;;
    -d)
      ARGS+="$1 "
      ;;
    -o|-g)
      ARGS+="$1 $2 "
      shift
      ;;
    -q)
      QLT="$1 $2 "
      shift
      ;;
    *)
      ARGS+="$1 "
      ;;
  esac
  shift
done

exec Brotli $QLT $ARGS
