## @file
# Azure Pipeline build file for a build using Windows and CLANGPDB
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
    - stable/*
  always: true

pr:
- master
- stable/*

variables:
  - template: templates/defaults.yml

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'CLANGPDB'
    vm_image: ${{ variables.default_windows_vm }}
    arch_list: "X64,AARCH64"
    usePythonVersion: ${{ variables.default_python_version }}
    extra_install_step:
    - powershell: choco install opencppcoverage; Write-Host "##vso[task.prependpath]C:\Program Files\OpenCppCoverage"
      displayName: Install Code Coverage Tool
      condition: and(gt(variables.pkg_count, 0), succeeded())
