## @file
# GNU/Linux makefile for Python tools build.
#
# Copyright (c) 2007 - 2010, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

all:

clean:
	find . -name '*.pyc' -exec rm '{}' ';'

