## @file
# Windows makefile for Python tools build.
#
# Copyright (c) 2010 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

all:

clean:
cleanall:  
  @del /f /q $(BASE_TOOLS_PATH)\Source\Python\*.pyc

