## @file
# GNU/Linux makefile for 'TianoCompress' module build.
#
# Copyright (c) 2007 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= ..

APPNAME = TianoCompress

LIBS = -lCommon

OBJECTS = TianoCompress.o

include $(MAKEROOT)/Makefiles/app.makefile
