## @file
# Windows makefile for 'TianoCompress' module build.
#
# Copyright (c) 2007 - 2010, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
!INCLUDE ..\Makefiles\ms.common

APPNAME = TianoCompress

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = TianoCompress.obj

!INCLUDE ..\Makefiles\ms.app

